import { Image, Pressable, Switch, View } from 'react-native';
import { useState } from 'react';
import ScreenContainer from './ScreenContainer';
import { AppText } from '../components/Typography';
import { SectionTitle } from '../components/Cards';
import { clips, episodes, user, characters } from '../api/mockData';
import { tap } from '../utils/haptics';

export default function ProfileScreen() {
  const [spoilers, setSpoilers] = useState(user.spoilers);
  async function toggle(value) { await tap(); setSpoilers(value); }
  return <ScreenContainer contentClassName="px-0 pb-8"><View className="bg-primary px-5 pb-8 pt-10"><AppText className="text-white" weight="heading">← Perfil</AppText><View className="mt-5 flex-row items-center"><Image source={user.avatar} className="h-16 w-16 rounded-full border-2 border-white"/><View className="ml-3"><AppText className="text-xs text-white/80">Bienvenido</AppText><AppText className="text-white" weight="heading">{user.name}</AppText></View></View></View><View className="px-4 pt-4"><View className="flex-row items-center justify-between"><AppText className="text-sm text-ink" weight="heading">Gestión de spoilers</AppText><Switch value={spoilers} onValueChange={toggle} trackColor={{ true: '#F44336', false: '#A0A0A0' }} /></View><View className="mt-4 flex-row gap-3"><View className="flex-1 rounded-2xl bg-white p-4"><AppText className="text-sm text-ink" weight="heading">Resumen de actividad</AppText><AppText className="mt-1 text-xs text-muted">Episodios vistos</AppText><AppText className="text-2xl text-primary" weight="heading">{user.watched}</AppText></View><Pressable onPress={tap} className="flex-1 rounded-2xl bg-white p-4"><AppText className="text-sm text-ink" weight="heading">↗ Compartir</AppText><AppText className="mt-1 text-xs text-muted">con tus amigos</AppText></Pressable></View><SectionTitle title="Episodios vistos"/>{episodes.map((episode)=><View key={episode.id} className="mb-2 flex-row rounded-2xl bg-white p-2"><Image source={episode.image} className="h-16 w-24 rounded-xl"/><View className="ml-3 flex-1 justify-center"><AppText className="text-xs text-ink" weight="heading">{episode.title}</AppText><AppText className="text-[10px] text-muted">T{episode.season} · EP {episode.episode}</AppText></View></View>)}<SectionTitle title="Detrás de cámaras"/><View className="flex-row gap-2">{clips.map((clip)=><Image key={clip.id} source={clip.image} className="h-20 flex-1 rounded-xl" />)}</View><SectionTitle title="Vida de los personajes"/><View className="flex-row justify-between">{characters.slice(0,4).map((character)=><View key={character.id} className="items-center"><Image source={character.image} className="h-14 w-14 rounded-full"/><AppText className="mt-1 text-[10px] text-ink">{character.name}</AppText></View>)}</View><SectionTitle title="Memes"/><View className="flex-row gap-2">{characters.slice(0,3).map((character)=><Image key={character.id} source={character.image} className="h-20 flex-1 rounded-xl" />)}</View></View></ScreenContainer>;
}
