const images = {
  malcolm: require('../../assets/images/malcolm.jpg'),
  reese: require('../../assets/images/reese.jpg'),
  dewey: require('../../assets/images/dewey.jpg'),
  francis: require('../../assets/images/francis.jpg'),
  lois: require('../../assets/images/lois.jpg'),
  hal: require('../../assets/images/hal.jpg'),
  stevie: require('../../assets/images/stevie.jpg'),
  herkabe: require('../../assets/images/herkabe.jpg'),
  epGraduacion: require('../../assets/images/ep-graduacion.jpg'),
  epHalloween: require('../../assets/images/ep-halloween.jpg'),
  epHomeAlone: require('../../assets/images/ep-home-alone.jpg'),
  epFlechazos: require('../../assets/images/ep-flechazos.jpg'),
  epZoo: require('../../assets/images/ep-zoo.jpg'),
  clipMalcolmMath: require('../../assets/images/clip-malcolm-math.jpg'),
  clipHalCoches: require('../../assets/images/clip-hal-coches.jpg'),
  clipReeseCocina: require('../../assets/images/clip-reese-cocina.jpg'),
  avatarJuan: require('../../assets/images/avatar-juan.jpg'),
  logo: require('../../assets/images/logo-malcolm-verse.png'),
  loginBg: require('../../assets/images/login-bg.jpg'),
  btsBloopers: require('../../assets/images/bts-bloopers.jpg'),
  btsEntrevista: require('../../assets/images/bts-entrevista.jpg'),
  btsRodaje: require('../../assets/images/bts-rodaje.jpg'),
  memeDewey1: require('../../assets/images/meme-dewey-1.jpg'),
  memeDewey2: require('../../assets/images/meme-dewey-2.jpg'),
  memeDewey3: require('../../assets/images/meme-dewey-3.jpg'),
};

export default images;
